stages:
- name: Build & Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/charluv:v1
      pushRemote: true
      registry: index.docker.io
timeout: 60
branch:
  include:
  - trunk
notification: {}
