// AUTO-GENERATED icon shim. Re-exports Phosphor (duotone, set globally via
// IconContext in App.tsx) under the Lucide names the app already uses, so call
// sites stay unchanged. To swap icon sets again, edit only this file.
export {
  Activity,
  Warning as AlertTriangle,
  TextAlignLeft as AlignLeft,
  Archive,
  ArchiveBox as ArchiveRestore,
  ArrowFatLeft as ArrowBigLeft,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Book,
  BookOpen as BookPlus,
  Robot as Bot,
  Brain,
  Briefcase,
  Camera,
  Check,
  CheckSquare,
  CaretDown as ChevronDown,
  CaretDoubleLeft as ChevronFirst,
  CaretDoubleRight as ChevronLast,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretDoubleLeft as ChevronsLeft,
  CaretUp as ChevronUp,
  Question as CircleHelp,
  XCircle as CircleX,
  Gear as Cog,
  Coin as Coins,
  Compass,
  AddressBook as Contact,
  Copy,
  Crown,
  Backspace as Delete,
  DiceFive as Dices,
  DownloadSimple as Download,
  CloudArrowDown as DownloadCloud,
  DownloadSimple as DownloadIcon,
  Barbell as Dumbbell,
  PencilSimple as Edit,
  Eye,
  EyeSlash as EyeOff,
  FileText as FileCheck,
  FileText,
  FileX,
  Flag,
  Globe,
  GlobeHemisphereWest as Globe2,
  GraduationCap,
  DotsSixVertical as GripHorizontal,
  Hash,
  Heart,
  Handshake as HeartHandshake,
  Question as HelpCircle,
  Image,
  ImageSquare as ImagePlus,
  ImageSquare as ImageUp,
  DownloadSimple as Import,
  Info,
  ListBullets as LayoutList,
  Leaf,
  FunnelSimple as ListFilter,
  SpinnerGap as LoaderCircle,
  SignIn as LogIn,
  Envelope as Mail,
  EnvelopeSimple as MailQuestion,
  Megaphone,
  List as Menu,
  ChatCircle as MessageCircle,
  ChatCircleDots as MessageCirclePlus,
  Microphone as Mic,
  MinusCircle,
  Moon,
  DotsThree as MoreHorizontal,
  ArrowRight as MoveRight,
  Pause,
  PauseCircle,
  PencilSimple as Pencil,
  PersonSimple as PersonStanding,
  Play,
  Plus,
  PlusCircle,
  Plus as PlusIcon,
  Power,
  Radio,
  ArrowsCounterClockwise as RefreshCcw,
  ArrowsClockwise as RefreshCw,
  RepeatOnce as Repeat1,
  ArrowCounterClockwise as RotateCcw,
  FloppyDisk as Save,
  FloppyDisk as SaveIcon,
  PaperPlaneRight as Send,
  Gear as Settings,
  ShoppingBag,
  ShoppingCart,
  CellSignalFull as Signal,
  Sliders,
  SlidersHorizontal,
  Smiley as Smile,
  SortAscending as SortAsc,
  SortDescending as SortDesc,
  Sparkle as Sparkles,
  SpeakerHigh as Speaker,
  Square,
  Star,
  Terminal,
  ThumbsUp,
  Trash,
  Trash as TrashIcon,
  ArrowArcLeft as Undo2,
  UploadSimple as Upload,
  User,
  Users,
  SpeakerHigh as Volume2,
  SpeakerSlash as VolumeX,
  MagicWand as Wand2,
  MagicWand as WandSparkles,
  X,
  XSquare,
  Lightning as Zap,
} from 'phosphor-solid'

// Phosphor's prop/context types under the names the app used from lucide.
export { IconContext, DiscordLogo } from 'phosphor-solid'
export type { IconProps, IconProps as LucideProps } from 'phosphor-solid'

// Vendored: phosphor-solid 1.1.5 ships no MaskHappy, so this is the official
// Phosphor duotone SVG wrapped to read IconContext like the real icons.
export { default as MaskHappy } from './icons/MaskHappyIcon'
